using UnityEngine;
using UnityEngine.SceneManagement;

public class CambioEscena : MonoBehaviour
{
    public string nombreEscena; //Asignar el nombre de la escena en el inspector

    void OnTriggerEnter(Collider other)
    {
        //Comprobar si el objeto con el que colisionas tiene el tag "enemigo"
        if (other.gameObject.CompareTag("enemigo"))
        {
            //Mostrar un mensaje en la consola de que se detect贸 el disparador
            Debug.Log("Se detect贸 el disparador con el enemigo");

            //Cambiar a la escena con el nombre asignado en modo single (reemplaza la escena actual)
            SceneManager.LoadScene(nombreEscena, LoadSceneMode.Single);

            //Mostrar un mensaje en la consola de que se carg贸 la escena
            Debug.Log("Se carg贸 la escena " + nombreEscena);
        }
    }
}
